### ISSUE TITLE
Request failed with status code 400

### ISSUE THREAD

**Issue by jonathanmauer** [tobilg/facebook-events-by-location-core#29]
Everything is fine, i changed anything and start getting this error

```
Request failed with status code 400
    at createError (.../node_modules/axios/lib/core/createError.js:16:15)
    at settle (.../nices-server/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (.../nices-server/node_modules/axios/lib/adapters/http.js:192:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

i think could be some return that has changed in the graph api

**Comment by tobilg** [comment]
How are you using it, and are you sure you’re using an app access token?

**Comment by jonathanmauer** [comment]
Yes i'm using an app access token, as i said, everything is fine. After some tests, i find this error when the api try to get events information.
```
"(#200) Access to this data is temporarily disabled for non-active accounts due to changes we are making to the Facebook Platform"
```

Looks the Facebook restricted some information from events, but i could not find which in specific.

ps: I have all the necessary permissions

**Comment by tobilg** [comment]
The error message is a bit strange, because when using an app access token, no user account is involved. Removing the events.fields basically renders the tool as meaningless

**Comment by BigFoppa** [comment]
Facebook has shut down access to some data using the Graph API. This is in response to the Analytica scandal. We can only wait for more information.

https://newsroom.fb.com/news/2018/03/hard-questions-cambridge-analytica/

https://developers.facebook.com/status/issues/205942813488872/

https://stackoverflow.com/questions/49417886/why-does-facebook-graph-api-say-my-account-is-non-active

/Big

**Comment by tobilg** [comment]
Thanks @bigfoppa! The error message couldn’t suck much more tbh, and FB is making strange moves. 

I can only imagine that the problem lies in the attendance/rsvp counts, because IMO these are the only things related to users. I’ll try to very that over the weekend.

**Comment by BigFoppa** [comment]
All data from Events is blocked for the moment. You can using the Graph Explorer see that events-data is blocked to apps. Suck, is an understatement. The error you get is:

{
  "error": {
    "message": "(#200) Access to this data is temporarily disabled for non-active accounts due to changes we are making to the Facebook Platform",
    "type": "OAuthException",
    "code": 200,
    "fbtrace_id": "GSO/a25jzqP"
  }
}

The "non-active accounts" meaning is a bit cryptic. But all apps are blocked for Events-data. A call like this gives the error above för an app (not for Graph Explorer):

?ids=179082445563485&fields=id,name,events.fields(id)

/Big

**Comment by tobilg** [comment]
If this is correct, then it’s one of the most stupid things ever. Event Data would have nothing to do with user data if they’d just remove the attending/maybe/declined counts. 

Not very well thought out apparently. Not that this surprises me.

**Comment by tobilg** [comment]
I tested this today, and unfortunately there doesn't seem to be a way to access events data with an app access token. 

I used the User Access Token from the Graph API Explorer to run the tests of this project, and it was successful. Maybe this could be an intermediate workaround?

**Comment by vrgomes** [comment]
Hi tobilg what steps did you take to make it work through User Access Token?
In the past I made this steps:
1 - You have to activate apps in your facebook profile (https://www.facebook.com/settings?tab=applications)
2 - Register in https://developers.facebook.com/
3 - Create an app. It will generate an id.
4 - Go to https://developers.facebook.com/tools/accesstoken/ -> get the App Token

**Comment by tobilg** [comment]
@vrgomes You can go to https://developers.facebook.com/tools/explorer/145634995501895/ and just copy the access token from there.

**Comment by BigFoppa** [comment]
Hmm, I always use a user-token in my app, Eventmap4u, and it doesn't work now. I can only get it to work within Graph Explorer (or if token is copied from GE) . I hope you can prove me wrong.

/Big

**Comment by tobilg** [comment]
@BigFoppa that's not what I was trying to say. If you're using the (User) access token copied from the Graph Explorer, it seems to work when passing it as `FEBL_ACCESS_TOKEN` env var. But it won't be possible if you use User access tokens generated by your app itself, at least at the moment.

**Comment by BigFoppa** [comment]
@tobilg we were writing at the same time, read your latest post after mine. We have the same understanding. The token from GE can be used for testing, but it is short-lived and expires too soon to be used in production.

/Big

**Comment by znortr** [comment]
Try to use an access token  from an app that point to a real site online and not to localhost.
In my case, after this change, the api started to work again.

**Comment by vrgomes** [comment]
@znortr can you explain how to configure that?

Greetings.

**Comment by znortr** [comment]
@vrgomes If you Look in your Facebook app dashboard you can see the domain app and the site url fields. 
Try to fill:
the domain app  with your online site name 
and the  site url with your online site url 
I'm not sure if in this way work, maybe you can try to create a new app.
I have two apps,  one pointed to localhost (that I had used till this morning) and another one pointed to my site so I simply replaced  the  access token from one to another and it worked.

**Comment by tobilg** [comment]
@znortr Thanks for the hint! I just tried to verify this behavior... Unfortunately I couldn't reproduce. I also tried to create a new app with the procedure you described, but not success either.

Are you using an app access token, or a user access token?

**Comment by znortr** [comment]
@tobilg I'm usig an app access token........
but, maybe I'm not in the right place, I'm referring to
 "Search Facebook events by location (as a service)" with Docker 
and not to "facebook-events-by-location-core"

**Comment by tobilg** [comment]
Well, you're in the wrong project then, but `facebook-events-by-location` uses `facebook-events-by-location-core` to get the events from FB. This can't be the reason why it works/doesn't work.

**Comment by znortr** [comment]
I'm not a developer so I do not know what to say, but I can say that, in my case, it work, I just checked, and today, after switching the access token, I downloaded about 15,000 events.

Here my app config:
app domain : xevent.it
site url : http://xevent.it

access token: **app_id**|**secret_key**
_(I use the same access token in a FB api graph to download events one by one in the online site)_

Let me know if you need some more info on this. 

(My guessing)
Since, the error message is _"Access to this data is temporarily disabled for inactive accounts"_ it makes me think that apps  not used in a real site are considerated inactive by the FB's "genes"  blocking it, but is puzzling that even the new apps do not work. (I have not tried, I believe you on the word)

**Comment by jonathanmauer** [comment]
Has anyone managed to make it work?

I set it up as the @znortr said, but doesnt work, maybe i have placed the app domain and site url in wrong place

**Comment by xtebs** [comment]
I just was able to make a (very fragile) WA. 
On Graph API Explorer you request a 'Page Access Token' from some page you have on facebook.
In my case, i had exactly the page of my app. 
When you have it just ada it manually to the URL you use "facebook-events-by-location" service.
example:
`http://localhost:3002/events?lat=38.687570912250685&lng=-9.354657&distance=1000&sort=venue&accessToken=<<big_huge_token>>`
It worked for me until a better solution comes.

**Comment by tobilg** [comment]
Thanks @xtebs. I'm quite sure that you only got a short-lived page access token, which you can check at https://developers.facebook.com/tools/debug/accesstoken

As it was generated by the Graph API Explorer app, you can't exchange it for a long-lived token, because you don't know the client secret (see https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension).

**Comment by xtebs** [comment]
Thanks for the heads-up @tobilg .I totally agree with you (unfortunately) . In my use-case I will need a lot of manual work until something better comes up.

**Comment by jonathanmauer** [comment]
Looks like everything working as well now

**Comment by JosteinKringlen** [comment]
@jonathanmauer Did you do anything special to make it work? I've tried using both app access token and user access token, but the closes I have gotten was getting an empty response when using user access token from graph explorer..

**Comment by jonathanmauer** [comment]
its working with both app and user access tokens. I think facebook is analising all the apps before granting permissions.

ps: Before i added domain and url from my api and it did not work, but... it may this have influenced

**Comment by aurabhi** [comment]
@jonathanmauer @JosteinKringlen I am still not able to access the api's. I am using user access token. Any suggestions?

**Comment by vrgomes** [comment]
Did anyone submit the App for Review?
When I click on that it show a list of permissions but all are user related. I don't see any related to Events. What permissions are needed?
![screenshot capture - 2018-03-28 - 09-25-31](https://user-images.githubusercontent.com/3107574/38017450-fed522b0-3269-11e8-9eb4-7fa09e223028.png)

**Comment by tobilg** [comment]
As using the `events` object doesn't require specific permission if it's privacy is set to `OPEN`, I'd assume that it isn't necessary to submit the app to app review (see https://developers.facebook.com/docs/graph-api/reference/event).

**Comment by tobilg** [comment]
This seems to be the bugs where FB tracks the issue(s): https://developers.facebook.com/bugs/1628695207221561/

I just commented, and am curious if I receive a response. And if so, what it will say...

**Comment by jonathanmauer** [comment]
i'm getting the same error again, it works for days and then stop again :/

**Comment by tobilg** [comment]
There‘s an update from FB: https://newsroom.fb.com/news/2018/04/restricting-data-access/

I’ll remove the attendance fields today and publish a new version, Inhipe this will fix the problems. I’ll announce the new version in this issue, so that you can test.

**Comment by DavidTomic** [comment]
@tobilg Facebook said: "And in the future, only apps we approve that agree to strict requirements will be allowed to use the Events API"

I think this means that we will have to request permissions for event API on the Facebook dashboard.

**Comment by tobilg** [comment]
I think the 

> And in the future, only apps we approve that agree to strict requirements will be allowed to use the Events API

notion is a bit non-sensical, as it doesn't share user data once the attendance fields are removed, but well... I guess they just can.

There is no specific permission for the bare public events yet, so I'd assume that this takes a while until  this comes in effect. But who knows, it's FB after all.

**Comment by tobilg** [comment]
I now see 

`OAuth "Facebook Platform" "insufficient_scope" "(#200) Access to this data is temporarily disabled for non-active apps or apps that have not recently accessed this data due to changes we are making to the Facebook Platform. https://developers.facebook.com/status/issues/205942813488872/"` messages and 403s with my test apps.

I just published version `0.11.0` to npm, please test and report back. Thanks!

**Comment by vrgomes** [comment]
Hi, I have updated to the last version but I still getting 403 , -1.
I already filled all the fields on the Facebook control panel but it looks like it doesn't fix the issue also.

**Comment by DavidTomic** [comment]
@vrgomes if you go to the Facebook app dashboard you will see(at least I see) message:
"We are not reviewing apps at this time due to changes we are making to the Facebook Platform."

So we will have to wait for Facebook to finish his work.

**Comment by tobilg** [comment]
I interpret

> Access to this data is temporarily disabled for non-active apps or apps that have not recently accessed this data

like that if you currently have a (utilized) app, it should work. Even without a review. The app review is normally only for apps which make use of OAuth permissions, which are as if today not necessary to access the public event data.

**Comment by jonathanmauer** [comment]
@tobilg I have permission for user_events and rsvp_status and still not working, i tested with user and app access tokens. Any suggestions?

**Comment by jonathanmauer** [comment]
Am I the only one who can not access event information?

**Comment by znortr** [comment]
@jonathanmauer Unfortunately not......

read this
[https://developers.facebook.com/blog/post/2018/04/04/facebook-api-platform-product-changes/](url)
and this
[https://developers.facebook.com/docs/graph-api/changelog/breaking-changes#events-4-4](url)

I can't access event data with app token, anymore, but I still access data with user token.......(I'm confused)

**Comment by tobilg** [comment]
Quote from https://developers.facebook.com/docs/graph-api/changelog/breaking-changes#events-4-4

> All apps, including formerly approved apps, must undergo App Review in order to gain access to the API.

> GET /events — You can no longer get the following edges:

> attending
> comments
> declined
> feed
> interested
> live_videos
> maybe
> noreply
> photos
> pictures
> posts
> videos

The edge should be fine, because the project doesn't use them (anymore). I think everyone now needs to apply to the app review process to get their apps granted permissions to access the `GET /events` endpoint.

**Comment by dtomicAZ** [comment]
@tobilg Is there any image we can get from event, or from place where event is occurring?

**Comment by vrgomes** [comment]
How do you apply for app review?
On my case it shows:
![screenshot capture - 2018-04-13 - 09-06-22](https://user-images.githubusercontent.com/3107574/38723778-0dac4db2-3efa-11e8-95ba-d9e5eb5b3048.png)

There is no option to select the events. And without selecting something the button to apply is disabled.

**Comment by tobilg** [comment]
What do you mean with "image" @DavidTomic? The programmatic access via the Graph API to the events have been restricted by FB. You need to have a reviewed app to get access to it, as described in my last post and the FB breaking change document.

**Comment by dtomicAZ** [comment]
@tobilg I understand I need to go through app review process, but I am interested when I get approved by FB, and when I call GET /events, is there any imageUrl here of event or place?

**Comment by tobilg** [comment]
As far as I understand it, it must undergo "feature review" as outlined at https://developers.facebook.com/docs/apps/review/feature?locale=en_EN#how-to-submit-for-feature-review

**Comment by tobilg** [comment]
@DavidTomic The output format is documented at https://github.com/tobilg/facebook-events-by-location-core/blob/master/schema/events-response.schema.json 

There are cover and profile pictures for the event and the venue.

**Comment by kwstasna** [comment]
@tobilg bump for the question of @vrgomes !
I don't understand which options should we choose !

**Comment by znortr** [comment]
As far I understand at this page

https://developers.facebook.com/docs/graph-api/reference/page/events/

> Reading Page events **requires** a valid **Page access token** or **User access token** with basic permissions

it seem, that looking for events ids on the page,  requires that the owner of the page gives the permission to the app. (hope I have misunderstood).

**Comment by dtomicAZ** [comment]
@znortr hmm, check here:
https://developers.facebook.com/docs/graph-api/reference/event
It says:
Any access token can be used to retrieve events with privacy set to OPEN.

**Comment by znortr** [comment]
@dtomicAZ  Yes I agree... if... You know the event id, its clear!
But to know the **event id by location** must to query the page.......

**Comment by jonathanmauer** [comment]
all of this is very strange because i'm still seeing apps using events api without any problems, what we should do to get this work??? D:

**Comment by tobilg** [comment]
Well, I think the things that were mentioned by @znortr and @dtomicAZ are not the root problem: Still https://developers.facebook.com/docs/graph-api/changelog/breaking-changes#pages-4-4 seems to apply, and FB has currently stopped reviewing apps apparantly.

https://developers.facebook.com/docs/apps/review states that 

> Beginning April 4, 2018, all apps, including those formerly approved, must undergo App Review in order to gain access to the Events API, Groups API, and Pages API. Apps accessing the Events API and Groups API will lose access and require review once App Review resumes. For apps using Pages API, review will be required once App Review resumes or access will be removed.

The suggested "Feature Review" (https://developers.facebook.com/docs/apps/review/feature) doesn't contain the `Events API`, as said on the other page. Seems like a deadlock to me at the moment.

**Comment by adf47** [comment]
Any updates/ideas on when the Events API will reopen? I saw this newsletter today, but it is confusing me because they make it should like the Events API is open, and that they have just removed one aspect of it. However, I am still not able to get any event data.

Here is the link to the newsletter: 
https://developers.facebook.com/blog/post/2018/04/24/new-facebook-platform-product-changes-policy-updates/?utm_campaign=developer-newsletter-april-2018&utm_medium=email&utm_source=developer-newsletter-april-2018-email&utm_location=2-policy-changes&mkt_tok=eyJpIjoiTWpReU9XRXhOalF3WTJFNCIsInQiOiIyOGJlaDVcL0tubXBsem44SEJtUld5OVlvT0MrWWFBeGR1UitUaVdMM0RabHhOQXBxODhcL0p0d2RGTENRTUhLWnhLZXQ1VzFvT3M2ZlRRTGVGdXlQbUc1MW9aanZzTStpK3I4S0lvZDZ6WEc1Q1ZEdHFGQ3E1MTlUWjhWVE9GMkFwIn0%3D

**Comment by jonathanmauer** [comment]
@adf47 sadly there is nothing to do, only wait. :/

**Comment by vrgomes** [comment]
Saw this: https://messenger.fb.com/newsroom/re-opens-app-review-launches-new-products-at-f8/

**Comment by adf47** [comment]
@vrgomes this is good news! Do you happen to know what features you’re supposed to choose to use the api and the events api?

**Comment by lostpebble** [comment]
It appears that they still are silent on the events API side of things. Can't see any feature we can select that relates to it.. only thing I could think that's slightly similar is the "Page Public Content Access", but that has no mention of events on it and seems to relate to other kinds of page data.

**Comment by tobilg** [comment]
Still no consistent communication from the FB side IMO. There's 

* https://developers.facebook.com/blog/post/2018/05/01/investing-in-facebook-developer-community/
* https://developers.facebook.com/blog/post/2018/05/01/enhanced-developer-app-review-and-graph-api-3.0-now-live/

but still no way to submit to app review regarding the Events API...

**Comment by jonathanmauer** [comment]
currently today im not getting #200 anymore, but get the following error:
```
{
   "error": {
      "message": "(#100) Tried accessing nonexisting field (events) on node type (PlaceInformation)",
      "type": "OAuthException",
      "code": 100,
      "fbtrace_id": "C1a+yw37kKq"
   }
}
```

**Comment by paulvaneijden** [comment]
You can only apply for app review of user_events if you have been previously approved before the mayor overhaul.

**Comment by tobilg** [comment]
IMO this is not related to user_events. Seems like you need to have access to the Places API according to the error message from @jonathanmauer...

**Comment by vrgomes** [comment]
Now I'm having empty responses: {"events":[],"metadata":{"venues":16,"venuesWithEvents":0,"events":0}}

**Comment by jonathanmauer** [comment]
@paulvaneijden if that is the case, I had permission previousl
@tobilg The errors from graph stopping, but now we receive empty array, can it be related to the "Public content of pages" permission in app review?

**Comment by kaitoqueiroz** [comment]
I'm getting this error, the app is needed to be published or development mode is valid?
`{
   "error": {
      "message": "(#100) Tried accessing nonexisting field (emails) on node type (PlaceInformation)",
      "type": "OAuthException",
      "code": 100,
      "fbtrace_id": "EZQuCiiXDxp"
   }
}`

**Comment by quentinhayot** [comment]
The field "events" doesn't exist anymore in the Places documentation:  
https://developers.facebook.com/docs/places/fields

**Comment by kwstasna** [comment]
@quentinhayot maybe they forgot it

**Comment by tobilg** [comment]
Seems like they really removed it: https://developers.facebook.com/tools/explorer/?method=GET&path=10150167889496698%3Ffields%3Devents&version=v3.0

yields 

```javascript
{
  "error": {
    "message": "(#100) Tried accessing nonexisting field (events) on node type (PlaceInformation)",
    "type": "OAuthException",
    "code": 100,
    "fbtrace_id": "BnqgqBWSWkJ"
  }
}
```

**Comment by hzitoun** [comment]
@vrgomes did you get a solution to make it work again please?

**Comment by BigFoppa** [comment]
Hi, I have been reading the documentation of v3.0 and there is says that Events is still part of the Page fields. But they have changed so that the Place.Id is not the same as Page.Id. Read here: https://developers.facebook.com/docs/graph-api/changelog/version3.0#places-graph

Doing a search for places you can get the Page. Test this in Graph Explorer:
search?type=place&center=59.3,18.06&distance=1000&fields=id,name,page.fields(id,name)

You can there see that the ids are not the same as they were before.

However, as I read the doc you should be able to get the Events information from the Page. 
But I have not been able to do that. Maybe someone else can figure that out. Or maybe we should file it as a bug. 
https://developers.facebook.com/docs/graph-api/reference/page/
https://developers.facebook.com/docs/graph-api/reference/page/events/

/Big

**Comment by BigFoppa** [comment]
Looks like they have shut down access to Events.

https://developers.facebook.com/support/bugs/1697903980256107/

A sad day /Big

**Comment by tobilg** [comment]
Sad that they even can’t communicate in a straight manner. The FB guy seems to be quite confused himself to be honest. 

The reasoning behind apparently closing an API for **public** events by using data protection as argument seems effed up at best.

**Comment by xtebs** [comment]
They just launched "Facebook Local". It's an event finder and agenda. Hope
that this is not their way to kill any rival.

**Comment by tobilg** [comment]
As it’s FB, I pretty much assume this is exactly the case...

**Comment by hzitoun** [comment]
@jonathanmauer probably they do that manually?

**Comment by jonathanmauer** [comment]
@hzitoun I think that's impossible, i'm from a small city from brazil and can find events here in real time by the https://world.timeout.com/

**Comment by renatochaves** [comment]
@jonathanmauer it's not in real time, you can easily notice the difference in attending count when you check some of the original events in FB.
I suppose they crawl from FB every once in a while. Maybe they're leveraging their own cache for events that were created before the API changes and this page will become useless soon?

**Comment by lostpebble** [comment]
@jonathanmauer @renatochaves that is most likely the case, and the current situation we are facing with our app at the moment. Stale data from a month ago when the API stopped working.

**Comment by MicahSteinbrecher** [comment]
`body: '{"error":{"message":"(#10) To use \'Page Public Content Access\', your use of this endpoint must be reviewed and approved by Facebook. To submit this \'Page Public Content Access\' feature for review please read our documentation on reviewable features: https:\\/\\/developers.facebook.com\\/docs\\/apps\\/review.","type":"OAuthException","code":10,"fbtrace_id":"E5peukGfRn\\/"}}' } },`

Has anyone completed the app review process, and has that fixed the problem for them?

**Comment by jonathanmauer** [comment]
I'm waiting review process, as soon as I have an answer, I'll let you know if it works :)

**Comment by vrgomes** [comment]
Hi, I also saw that post from MicahSteinbrecher.
Now on the review page there is the option for Public Content Access. It must be this that can unlock the Event search.

**Comment by quentinhayot** [comment]
Not yet I'm afraid :(

**Comment by ifokeev** [comment]
Sent my app for a review with `user_events` permission and have no answer for 2 weeks already =\

**Comment by jonathanmauer** [comment]
Ok, so now i'm able to pull events, but only the one's that i already marked as attending/maybe/etc

It's ridiculous from Facebook open events node that way

OBS: I have to make changes in this lib to get events by page and not by place.

**Comment by quentinhayot** [comment]
How did you do ?
With API Explorer and an access token with all permissions I can't access my events.

**Comment by quentinhayot** [comment]
Ok, I can make it work with API Explorer with an App Token from a development app.

**Comment by ifokeev** [comment]
I see events accessed with debug APP token from https://developers.facebook.com/tools/accesstoken/

**Comment by jonathanmauer** [comment]
Its seems there is no way to get upcoming events. 😕

**Comment by quentinhayot** [comment]
For public pages you mean ?
I can retrieve upcoming events I'm directly linked to (attending, interested, maybe, host) and events hosted by a page I'm linked to (admin).

**Comment by tobilg** [comment]
@jonathanmauer @quentinhayot I don't really think that trying to use `user_events` is the right way. You'll also want to get events you're not "linked" to I'd assume...

Going through app review for https://developers.facebook.com/docs/apps/review/feature#reference-PAGES_ACCESS seems to be the way to go actually.

**Comment by quentinhayot** [comment]
I agree with you.
But as far as I understand: no link with an event (through an user or host page) = no data :(

**Comment by tobilg** [comment]
I currently *assume* that the "Page Public Content Access" will enable the access to public events from pages again. But this is nowhere explicitly stated in he FB docs, and there seems to be an ongoing confusion about this in the dev community (see https://developers.facebook.com/support/bugs/1697903980256107/). 

Has anyone been reviewed successfully on the above feature, and can confirm this works/doesn't work?

**Comment by quentinhayot** [comment]
There is no confusion:

> there is currently no permission available to apply for scraping public events. We have begun the process of updating the docs accordingly.

and

> Hi all, due to the platform changes this endpoint now requires either the access token of the page or a user access token of someone that is connected to the page like the user token of the page admin.

_No link, no data.™_

**Comment by lassegit** [comment]
So to conclude on this: As @xtebs mentioned, Facebook has launched its own event explorer app – [Facebook local](https://www.facebook.com/local/) – and therefore will likely permanently shut down access to events exploring, so they monopolize the market. Naturally branding the discontinued API access as privacy measure. 

This really sucks, I don't want to use Facebook. @tobilg would it make sense to set a notice in the readme file?

**Comment by tobilg** [comment]
Eventually, yes. There’s a lot of speculation and no clear message from FB regarding the Events API yet, and that’s the reason I didn’t do it yet.

**Comment by vrgomes** [comment]
My application got rejected. 
Anyone had success?

Greetings.

**Comment by kwstasna** [comment]
Mine also got rejected 🙅🏼 😡😡

**Comment by BigFoppa** [comment]
Did you get any reasons?

**Comment by kwstasna** [comment]
Feedback From Your Last Submission (6/13, 2:32am)
This permission is not required for your app's intended function, or it doesn't appear to enhance the user experience. Please review this reference for more details about all different permissions, including common and invalid use cases.
Notes From Your Reviewer
Please refer to this document for valid use cases. Thank you!
https://developers.facebook.com/docs/apps/review/feature#reference-PAGES_ACCESS

**Comment by adf47** [comment]
Does anyone know of another API or platform that could produce the same data? We all are looking for event data, I am curious if anyone knows any alternatives? 

There are platforms such as Eventbrite that have APIs to get the event data, but there terms are strict in that it seems like you cannot use the API to compete with them, which makes it difficult to use or get permission.

**Comment by lassegit** [comment]
@adf47 You could properly scrape Facebook using a HTML-crawler. Needless to say, a hassle. There are also some services that offer that as well, but haven't tried any of them.

**Comment by znortr** [comment]
@vrgomes The endpoint still exist but the response is empty..........

**Comment by mikestaub** [comment]
@znortr can you provide a code snippet of the curl command that returns an empty list? Perhaps your request is malformed or there are no events in that area.

**Comment by kaitoqueiroz** [comment]
What about read events from users?
We can create a base of events if you have a certain quantity of users.

**Comment by adf47** [comment]
@znortr I am having the same issue. Even on the graph explorer I can get no data on the events node to return

**Comment by znortr** [comment]
@mikestaub @adf47 Tested with regular api link and also on graph explorer with no success, tested also with page id !

But it seems that they restricted the api 
https://developers.facebook.com/docs/graph-api/reference/page/events/
`This is a restricted edge. You cannot request access at this time`
unfortunatly that's it ......

@kaitoqueiroz What do you mean ??
 I have no problem to get events from my registered users, I need to found a solution to get events by area like was before that the f..g Zuckerberg decide, with no reason, to kill our websites.

**Comment by kaitoqueiroz** [comment]
@znortr You can store a event from a registered user and provide to another users. If you have a good quantity of users, maybe you can have a good database of events by area.

It's not the best solution, of course. But it's better than nothing.

**Comment by tobilg** [comment]
I don't really think it makes a lot of sense to use User Events, because the most of the "professional events" are created by pages. You'd have to have a really large user group to have a decent amount of events available. 

I fear we reached a dead end with the Graph API and event data. No one I know of was able in the last months after the API changes to get access to the Event API data.

I added a hint in the README regarding this. Unfortunately, there's nothing more I can do at the moment.

**Comment by ShakeDigital** [comment]
What's everyone using as an alternative to Event API data? Is there a 'next best' available?

**Comment by hzitoun** [comment]
Any news?

**Comment by lifeact** [comment]
@hzitoun  I found and use  https://codecanyon.net/item/wordpress-automatic-plugin!

[image](https://user-images.githubusercontent.com/8957733/44825969-a0fc9a80-ac15-11e8-8241-8b9723588c7a.png)
)

**Comment by kaitoqueiroz** [comment]
@lifeact the link is offline.

https://codecanyon.net/item/wordpress-automatic-plugin/1904470
I've found this.

**Comment by lifeact** [comment]
@kaitoqueiroz
> https://codecanyon.net/item/wordpress-automatic-plugin/1904470
I've found this. 

Yes, it's as temporary  decide. Waiting for FB api (

**Comment by ghost** [comment]
@lifeact can you explain everything? 
Does it access to data using the Graph API and export events from facebook pages?

**Comment by tobilg** [comment]
@andreandev I think the comment from @lifeact has nothing to do with the actual problem. FB still hasn't opened up (and probably never will) the access to the Events via API. I highly doubt that a Wordpress plugin can actually get the data out of thin air.

**Comment by lifeact** [comment]
@andreandev No, it is not graph api,  Plugin parse last 6 events from page, group, etc. And give all data (date, time, content, GEO data, Street, image).  You can try live demo - http://preview.codecanyon.net/item/wordpress-automatic-plugin/full_screen_preview/1904470  (Try live demo! - An activation email will be sent to this email address.)

**Comment by tobilg** [comment]
@lifeact this doesn't solve the original question. Please don't advertise Wordpress plugins in this issue.

**Comment by lifeact** [comment]
@tobilg ok, sory, thise is not AD. I show my way to decide problem

**Comment by ghost** [comment]
A dig from the past 🚨
Any new/alternative on this?

**Comment by entin-hun** [comment]
I'm able to get events from pages I don't have a role in with {page-id}/events
Does it make a sense?

**Comment by kwstasna** [comment]
> I'm able to get events from pages I don't have a role in with {page-id}/events
> Does it make a sense?

@entin-hun Do you have a verified app in Facebook Developers ?

**Comment by entin-hun** [comment]
> > I'm able to get events from pages I don't have a role in with {page-id}/events
> > Does it make a sense?
> 
> @entin-hun Do you have a verified app in Facebook Developers ?

Our app's status is "Live", with the following permissions only:
LOGIN PERMISSIONS
email
public_profile

**Comment by kwstasna** [comment]
@entin-hun which Graph-API version ?

**Comment by entin-hun** [comment]
> @entin-hun which Graph-API version ?

latest, 3.3. (using the new beta and previous as well) Doesn't it work for you?

**Comment by lostpebble** [comment]
Definitely does not work for me. Says your app needs to get approval.

Are you sure you are not related to the page in any way? I've made that mistake before and got excited.

Otherwise, you must just be extremely lucky.

**Comment by kwstasna** [comment]
@lostpebble i don't think it as a luck. I'm sure he sees the events from his page, because i tried again now and its still a 400 😢

**Comment by estathop** [comment]
any luck folks getting somehow public events ?

**Comment by quentinhayot** [comment]
I think it's time to move on with this. With their recent "focus on privacy" announcements, there is probably zero chance that they allow access to this data ever again.

**Comment by estathop** [comment]
is there by any chance any window for research centers and researchers in general that participate in Horizon2020 projects to get access in this info ? I mean social media analytics is a study field and no one can solely rely on twitter

**Comment by lostpebble** [comment]
> I think it's time to move on with this. With their recent "focus on privacy" announcements, there is probably zero chance that they allow access to this data ever again.

This is actually public data.. always was. The API provided data on publically open events. Their excuse of "privacy" for shutting this endpoint down is ridiculous.

Let's not dance around the fact that this is FB giving the middlefinger to developers of their events API in order to have a monopoly on events information for their next product iterations. I hear they have a big focus on events coming up.

In any case, I agree. This ship has sailed.
